name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [melodic, noetic]

    name: Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ${{ matrix.ros_distribution }}-test

  test-boost-asio:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [noetic]

    name: Test (ROS ${{ matrix.ros_distribution }}, Boost Asio)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ${{ matrix.ros_distribution }}-test-boost-asio
